[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "databricks-etl-monitor"
version = "0.1.0a5"
description = "Metadata-driven ETL Process Monitoring Framework for Databricks / Delta Lake"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Nitin Mathew George" }
]
keywords = ["databricks", "delta-lake", "etl-monitoring", "pyspark", "adf", "unity-catalog"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = []

[project.optional-dependencies]
standalone = [
    "pyspark>=3.3",
    "delta-spark>=2.0",
]
dev = ["pytest>=7", "pytest-cov"]

[tool.setuptools.packages.find]
where = ["."]
include = ["etl_monitor*"]

[tool.setuptools.package-data]
"etl_monitor" = ["sample_usage/*"]
